# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-27 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import habr.models


class Migration(migrations.Migration):

    dependencies = [
        ('habr', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_reaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=habr.models.generic_filename),
        ),
    ]
